### ISSUE TITLE
design.firefox.com violates Mozilla web security guidelines

### ISSUE THREAD

**Issue by franziskuskiefer** [FirefoxUX/firefoxUX.github.io#7]
The [Mozilla web security guidelines](https://wiki.mozilla.org/Security/Guidelines/Web_Security) list HTTPS as mandatory for all Mozilla sites.
design.firefox.com doesn't support HTTPS because it's hosted on github.

**Comment by brassy-** [comment]
Duplicate https://github.com/FirefoxUX/photon/issues/88

**Comment by ExE-Boss** [comment]
I have solved this on [my website](https://exe-boss.tech) by using [Cloudflare’s HTTPS only feature](https://blog.cloudflare.com/how-to-make-your-site-https-only/), which uses [301 redirects](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) to enforce HTTPS and then [submitted the website to the HSTS preload list](https://hstspreload.org/?domain=exe-boss.tech).

---

P.S.: I was about to report this issue myself.
